version: "3.1"
services:
  mysql:
    build: ./book_store_db/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstoredb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    restart: on-failure
    networks:
      - airflow
volumes:
  mysql-data: