book_store:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: 'bookstore_role'
      database: 'bookstore_db'
      warehouse: 'bookstore_wh'
      schema: 'bookstore_schema'
      client_session_keep_alive: False
    
  target: dev