book_store:
  outputs:
    dev:
      type: snowflake
      account: ${SNOWFLAKE_ACCOUNT}
      user: ${SNOWFLAKE_USER}
      password: ${SNOWFLAKE_PASSWORD}
      role: 'bookstore_role'
      database: 'bookstore_db'
      warehouse: 'bookstore_wh'
      schema: 'bookstore_schema'
      client_session_keep_alive: False
    
    staging:
      type: snowflake
      account: ${SNOWFLAKE_ACCOUNT}
      user: ${SNOWFLAKE_USER}
      password: ${SNOWFLAKE_PASSWORD}
      role: 'bookstore_role'
      database: 'bookstore_db'
      warehouse: 'bookstore_wh'
      schema: 'stage_schema'
      client_session_keep_alive: False
    
  target: staging